from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CH_MAQUINA(object):
    def setupUi(self, CH_MAQUINA):
        CH_MAQUINA.setObjectName("CH_MAQUINA")
        CH_MAQUINA.resize(1366, 760)

        self.centralwidget = QtWidgets.QWidget(CH_MAQUINA)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, -1, 341, 98))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.acumulador = QtWidgets.QLabel(self.gridLayoutWidget)
        self.acumulador.setText("")
        self.acumulador.setObjectName("acumulador")
        self.gridLayout.addWidget(self.acumulador, 1, 1, 1, 1)
        self.instrucci = QtWidgets.QLabel(self.gridLayoutWidget)
        self.instrucci.setText("")
        self.instrucci.setObjectName("instrucci")
        self.gridLayout.addWidget(self.instrucci, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.totalMemoria = QtWidgets.QLabel(self.gridLayoutWidget)
        self.totalMemoria.setText("")
        self.totalMemoria.setObjectName("totalMemoria")
        self.gridLayout.addWidget(self.totalMemoria, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.pos_mem = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pos_mem.setText("")
        self.pos_mem.setObjectName("pos_mem")
        self.gridLayout.addWidget(self.pos_mem, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.valor = QtWidgets.QLabel(self.gridLayoutWidget)
        self.valor.setText("")
        self.valor.setObjectName("valor")
        self.gridLayout.addWidget(self.valor, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.pbTotalMen = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.pbTotalMen.setProperty("value", 24)
        self.pbTotalMen.setObjectName("pbTotalMen")
        self.gridLayout.addWidget(self.pbTotalMen, 6, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(380, 10, 491, 411))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spinKernel = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinKernel.setMaximum(999)
        self.spinKernel.setProperty("value", 79)
        self.spinKernel.setObjectName("spinKernel")
        self.gridLayout_2.addWidget(self.spinKernel, 10, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 9, 0, 1, 1)
        self.memoria = QtWidgets.QTableWidget(self.gridLayoutWidget_2)
        self.memoria.setObjectName("memoria")
        self.memoria.setColumnCount(5)
        self.memoria.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.memoria.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.memoria.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.memoria.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.memoria.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.memoria.setHorizontalHeaderItem(4, item)
        self.gridLayout_2.addWidget(self.memoria, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.pbMemoria = QtWidgets.QProgressBar(self.gridLayoutWidget_2)
        self.pbMemoria.setProperty("value", 24)
        self.pbMemoria.setObjectName("pbMemoria")
        self.gridLayout_2.addWidget(self.pbMemoria, 8, 0, 1, 1)
        self.pbKernel = QtWidgets.QProgressBar(self.gridLayoutWidget_2)
        self.pbKernel.setProperty("value", 24)
        self.pbKernel.setObjectName("pbKernel")
        self.gridLayout_2.addWidget(self.pbKernel, 11, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 5, 0, 1, 1)
        self.spinMemoria = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinMemoria.setSuffix("")
        self.spinMemoria.setMinimum(0)
        self.spinMemoria.setMaximum(9999)
        self.spinMemoria.setProperty("value", 100)
        self.spinMemoria.setObjectName("spinMemoria")
        self.gridLayout_2.addWidget(self.spinMemoria, 6, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 7, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(890, 10, 389, 85))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 1, 0, 1, 1)

        self.encender = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.encender.setMaximumSize(QtCore.QSize(57, 57))
        self.encender.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("on.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.encender.setIcon(icon1)
        self.encender.setIconSize(QtCore.QSize(57, 57))
        self.encender.setObjectName("encender")
        self.gridLayout_4.addWidget(self.encender, 0, 0, 1, 1)

        self.apagar = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.apagar.setMaximumSize(QtCore.QSize(57, 57))
        self.apagar.setAutoFillBackground(False)
        self.apagar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.apagar.setIcon(icon2)
        self.apagar.setIconSize(QtCore.QSize(57, 57))
        self.apagar.setObjectName("apagar")
        self.gridLayout_4.addWidget(self.apagar, 0, 1, 1, 1)

        self.imprimir = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.imprimir.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Imprimir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.imprimir.setIcon(icon3)
        self.imprimir.setIconSize(QtCore.QSize(57, 57))
        self.imprimir.setObjectName("imprimir")
        self.gridLayout_4.addWidget(self.imprimir, 0, 5, 1, 1)

        self.ejecutar = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.ejecutar.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ejecutar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ejecutar.setIcon(icon4)
        self.ejecutar.setIconSize(QtCore.QSize(57, 57))
        self.ejecutar.setObjectName("ejecutar")
        self.gridLayout_4.addWidget(self.ejecutar, 0, 2, 1, 1)

        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 1, 5, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 1, 2, 1, 1)

        self.abrir = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.abrir.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Abrir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.abrir.setIcon(icon5)
        self.abrir.setIconSize(QtCore.QSize(57, 57))
        self.abrir.setObjectName("abrir")
        self.gridLayout_4.addWidget(self.abrir, 0, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(890, 100, 91, 29))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(890, 120, 350, 250))
        self.label_13.setMaximumSize(QtCore.QSize(350, 250))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("monitor.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(890, 360, 61, 41))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(890, 380, 350, 250))
        self.label_15.setMaximumSize(QtCore.QSize(350, 250))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("impresora.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.monitor = QtWidgets.QLabel(self.centralwidget)
        self.monitor.setGeometry(QtCore.QRect(820, 680, 331, 161))
        self.monitor.setText("")
        self.monitor.setObjectName("monitor")
        self.impresora = QtWidgets.QLabel(self.centralwidget)
        self.impresora.setGeometry(QtCore.QRect(180, 700, 241, 81))
        self.impresora.setText("")
        self.impresora.setObjectName("impresora")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 160, 329, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.procesos = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.procesos.setObjectName("procesos")
        self.procesos.setColumnCount(6)
        self.procesos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.procesos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.procesos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.procesos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.procesos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.procesos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.procesos.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.procesos)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.variables = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.variables.setObjectName("variables")
        self.variables.setColumnCount(5)
        self.variables.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.variables.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.variables.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.variables.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.variables.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.variables.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.variables)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.etiquetas = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.etiquetas.setObjectName("etiquetas")
        self.etiquetas.setColumnCount(4)
        self.etiquetas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.etiquetas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.etiquetas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.etiquetas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.etiquetas.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.etiquetas)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(380, 420, 485, 211))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.editProgr = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_2)
        self.editProgr.setObjectName("editProgr")
        self.verticalLayout_2.addWidget(self.editProgr)
        self.errores = QtWidgets.QTextEdit(self.verticalLayoutWidget_2)
        self.errores.setObjectName("errores")
        self.verticalLayout_2.addWidget(self.errores)
        self.analizarSinta = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.analizarSinta.setObjectName("analizarSinta")
        self.verticalLayout_2.addWidget(self.analizarSinta)
        CH_MAQUINA.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CH_MAQUINA)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 26))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuEjecutar = QtWidgets.QMenu(self.menubar)
        self.menuEjecutar.setObjectName("menuEjecutar")
        self.menuInformaci_n = QtWidgets.QMenu(self.menubar)
        self.menuInformaci_n.setObjectName("menuInformaci_n")
        self.menuImprimir = QtWidgets.QMenu(self.menubar)
        self.menuImprimir.setObjectName("menuImprimir")
        CH_MAQUINA.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CH_MAQUINA)
        self.statusbar.setObjectName("statusbar")
        CH_MAQUINA.setStatusBar(self.statusbar)
        self.actionEncender = QtWidgets.QAction(CH_MAQUINA)
        self.actionEncender.setCheckable(False)
        self.actionEncender.setObjectName("actionEncender")
        self.actionApagar = QtWidgets.QAction(CH_MAQUINA)
        self.actionApagar.setObjectName("actionApagar")
        self.actionCargar_Programa = QtWidgets.QAction(CH_MAQUINA)
        self.actionCargar_Programa.setObjectName("actionCargar_Programa")
        self.actionPrograma = QtWidgets.QAction(CH_MAQUINA)
        self.actionPrograma.setObjectName("actionPrograma")
        self.actionSalir_del_S_O = QtWidgets.QAction(CH_MAQUINA)
        self.actionSalir_del_S_O.setObjectName("actionSalir_del_S_O")
        self.actionPaso_a_paso = QtWidgets.QAction(CH_MAQUINA)
        self.actionPaso_a_paso.setObjectName("actionPaso_a_paso")
        self.menuArchivo.addAction(self.actionEncender)
        self.menuArchivo.addAction(self.actionApagar)
        self.menuArchivo.addAction(self.actionCargar_Programa)
        self.menuArchivo.addAction(self.actionSalir_del_S_O)
        self.menuEjecutar.addAction(self.actionPrograma)
        self.menuEjecutar.addAction(self.actionPaso_a_paso)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEjecutar.menuAction())
        self.menubar.addAction(self.menuInformaci_n.menuAction())
        self.menubar.addAction(self.menuImprimir.menuAction())

        self.retranslateUi(CH_MAQUINA)
        self.actionSalir_del_S_O.triggered.connect(CH_MAQUINA.close)
        self.actionEncender.triggered.connect(self.encender.click)
        self.actionApagar.triggered.connect(self.apagar.click)
        self.actionCargar_Programa.triggered.connect(self.abrir.click)
        QtCore.QMetaObject.connectSlotsByName(CH_MAQUINA)

    def retranslateUi(self, CH_MAQUINA):
        _translate = QtCore.QCoreApplication.translate
        CH_MAQUINA.setWindowTitle(_translate("CH_MAQUINA", "Sistema Operativo CH - MÁQUINA"))
        self.label_4.setText(_translate("CH_MAQUINA", "Valor"))
        self.label_2.setText(_translate("CH_MAQUINA", "Posición de memoria"))
        self.label_5.setText(_translate("CH_MAQUINA", "Total de memoria"))
        self.label_3.setText(_translate("CH_MAQUINA", "Instrucción"))
        self.label.setText(_translate("CH_MAQUINA", "Acumulador"))
        self.label_11.setText(_translate("CH_MAQUINA", "KERNEL"))
        item = self.memoria.horizontalHeaderItem(0)
        item.setText(_translate("CH_MAQUINA", "POS"))
        item = self.memoria.horizontalHeaderItem(1)
        item.setText(_translate("CH_MAQUINA", "PROGRAMA"))
        item = self.memoria.horizontalHeaderItem(2)
        item.setText(_translate("CH_MAQUINA", "INSTRUCCIÓN"))
        item = self.memoria.horizontalHeaderItem(3)
        item.setText(_translate("CH_MAQUINA", "ARGUMENTO"))
        item = self.memoria.horizontalHeaderItem(4)
        item.setText(_translate("CH_MAQUINA", "VALOR"))
        self.label_9.setText(_translate("CH_MAQUINA", "Memoria"))
        self.label_10.setText(_translate("CH_MAQUINA", "MEMORIA"))
        self.label_16.setText(_translate("CH_MAQUINA", "MEMORIA DISPONIBLE"))
        self.label_22.setText(_translate("CH_MAQUINA", "OFF"))
        self.label_21.setText(_translate("CH_MAQUINA", "ON"))
        self.label_25.setText(_translate("CH_MAQUINA", "Impr"))
        self.label_23.setText(_translate("CH_MAQUINA", "Run"))
        self.label_24.setText(_translate("CH_MAQUINA", "Open"))
        self.label_6.setText(_translate("CH_MAQUINA", "Procesos"))
        item = self.procesos.horizontalHeaderItem(0)
        item.setText(_translate("CH_MAQUINA", "ID"))
        item = self.procesos.horizontalHeaderItem(1)
        item.setText(_translate("CH_MAQUINA", "PROGRAMAS"))
        item = self.procesos.horizontalHeaderItem(2)
        item.setText(_translate("CH_MAQUINA", "Nº INST."))
        item = self.procesos.horizontalHeaderItem(3)
        item.setText(_translate("CH_MAQUINA", "RB"))
        item = self.procesos.horizontalHeaderItem(4)
        item.setText(_translate("CH_MAQUINA", "RCL"))
        item = self.procesos.horizontalHeaderItem(5)
        item.setText(_translate("CH_MAQUINA", "RLP"))
        self.label_7.setText(_translate("CH_MAQUINA", "Variables"))
        item = self.variables.horizontalHeaderItem(0)
        item.setText(_translate("CH_MAQUINA", "POS"))
        item = self.variables.horizontalHeaderItem(1)
        item.setText(_translate("CH_MAQUINA", "PROG."))
        item = self.variables.horizontalHeaderItem(2)
        item.setText(_translate("CH_MAQUINA", "TIPO"))
        item = self.variables.horizontalHeaderItem(3)
        item.setText(_translate("CH_MAQUINA", "VARIABLES"))
        item = self.variables.horizontalHeaderItem(4)
        item.setText(_translate("CH_MAQUINA", "VALOR"))
        self.label_8.setText(_translate("CH_MAQUINA", "Etiquetas"))
        item = self.etiquetas.horizontalHeaderItem(0)
        item.setText(_translate("CH_MAQUINA", "POS"))
        item = self.etiquetas.horizontalHeaderItem(1)
        item.setText(_translate("CH_MAQUINA", "PROG."))
        item = self.etiquetas.horizontalHeaderItem(2)
        item.setText(_translate("CH_MAQUINA", "ETIQUETA"))
        item = self.etiquetas.horizontalHeaderItem(3)
        item.setText(_translate("CH_MAQUINA", "ARGUMENTO"))
        self.label_17.setText(_translate("CH_MAQUINA", "EDITOR DE PROGRAMAS CH"))
        self.analizarSinta.setText(_translate("CH_MAQUINA", "Actualizar archivo"))
        self.menuArchivo.setTitle(_translate("CH_MAQUINA", "Archivo"))
        self.menuEjecutar.setTitle(_translate("CH_MAQUINA", "Ejecutar"))
        self.menuInformaci_n.setTitle(_translate("CH_MAQUINA", "Información"))
        self.menuImprimir.setTitle(_translate("CH_MAQUINA", "Imprimir"))
        self.actionEncender.setText(_translate("CH_MAQUINA", "Encender"))
        self.actionApagar.setText(_translate("CH_MAQUINA", "Apagar"))
        self.actionCargar_Programa.setText(_translate("CH_MAQUINA", "Cargar Programa"))
        self.actionPrograma.setText(_translate("CH_MAQUINA", "Programa"))
        self.actionSalir_del_S_O.setText(_translate("CH_MAQUINA", "Salir del S.O."))
        self.actionPaso_a_paso.setText(_translate("CH_MAQUINA", "Paso a paso"))

